### ISSUE TITLE
Vue2 Example

### ISSUE THREAD

**Issue by viglucci** [ssleptsov/ninja-keys#12]
Thanks for creating this package! Although I am having some trouble integrating with Vue2, it seems very useful.

I understand that you've created this package mainly to work with several of your own Vue projects, so I was wondering if you have a working example using Vue2? I am not able to use Vue3 just yet, so hoping to get this working with Vue2.

The [Vue example](https://codesandbox.io/s/ninja-keys-demo-vue3-bps5w) seems to be using Vue3, and the `:data` with Vue2 doesn't seem to behave the same way (results in `[[object Object], ...]` serialized on the DOM element.

Thanks

**Comment by ssleptsov** [comment]
Hey @viglucci 
Thank you! Yes, it was already on one issue. I forget to add a link for codesandbox example.

Updated readme, but also here is a link with example: https://codesandbox.io/s/ninja-keys-demo-vue2-b129z

**Comment by viglucci** [comment]
@ssleptsov thanks! Works great!
