### ISSUE TITLE
How to custom the text content of footer

### ISSUE THREAD

**Issue by CNFeffery** [ssleptsov/ninja-keys#14]
Is it possible to custom the `to select`, `to navigate`, `to close` and `move to parent` text content in the footer?

**Comment by ssleptsov** [comment]
Hey @CNFeffery 
Yea, it's possible . Here is info about it in readme, 
But there was a typo in example, so maybe was not working. Fixed now.

[https://github.com/ssleptsov/ninja-keys/blob/main/README.md#change-or-hide-footer](https://github.com/ssleptsov/ninja-keys/blob/main/README.md#change-or-hide-footer)
