### ISSUE TITLE
Export css variable of content zIndex

### ISSUE THREAD

**Issue by alanaudi** [ssleptsov/ninja-keys#21]
Hi, I have some zIndex > 1 elements, and the modal is hidden behind them.
Since, there is no shadow for outer `div.modal`, it cannot be styled with shadow part method.
Is it possible to export zIndex varaible to be overwrited ?

Thanks for your great work.

**Comment by ssleptsov** [comment]
Yeah, sounds good @alanaudi 
I have added `zIndex` to new released 1.2.0 version.
Example to use in your css:
```css
ninja-keys {
  --ninja-z-index: 123;
}
```

**Comment by alanaudi** [comment]
@ssleptsov  thanks you very much for hotfixing this issue 🎉
I have used in my sveltekit blog !!! alanaudi/alog@e154684e6763081afffd0842517d2c390b756d14
