### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by fayazara** [ssleptsov/ninja-keys#7]
I get a modal open when I hit cmd + k, but wont render the list items. I used the same code from the codesandbox example which was mentioned.

<img width="1440" alt="Screenshot 08-11 at 18@2x" src="https://user-images.githubusercontent.com/15716057/140750814-b868b94d-421e-467f-96bd-6f5e08ab8c88.png">

I am on vue version **2.6.12**.

I am getting this below error.

`TypeError: Cannot read properties of null (reading 'map')` I think this below method `_flattern` is not getting its argument `members`, this is on `ninja-keys.js` _line: 262_. 

```
    key: "_flattern",
    value: function _flattern(members, parent) {
      var children = [];
      return members.map(function (mem) {
        var alreadyFlatternByUser = mem.children && mem.children.some(function (value) {
          return typeof value == 'string';
        });

        var m = _objectSpread(_objectSpread({}, mem), {}, {
          parent: mem.parent || parent
        });

        if (alreadyFlatternByUser) {
          return m;
        } else {
          if (m.children && m.children.length) {
            parent = mem.id;
            children = [].concat(_toConsumableArray(children), _toConsumableArray(m.children));
          }

          m.children = m.children ? m.children.map(function (c) {
            return c.id;
          }) : [];
          return m;
        }
      }).concat(children.length ? this._flattern(children, parent) : children);
    }
    ```

**Comment by fayazara** [comment]
Reproduced here - 

https://codesandbox.io/s/friendly-wood-65ghr?file=/src/App.vue

**Comment by ssleptsov** [comment]
hey @fayazara 
hm...so, vue2 CLI or babel config making `data` as an attribute and not passing it as an object for this build configuration. 
Because for vue3/vite it works fine. 

As a quick workaround, you can use it as "ref", here is forked with a working example 
[https://codesandbox.io/s/tender-water-b129z?file=/src/App.vue](https://codesandbox.io/s/tender-water-b129z?file=/src/App.vue)
