### ISSUE TITLE
Dynamic commands makes ninja keys jump randomly

### ISSUE THREAD

**Issue by fayazara** [ssleptsov/ninja-keys#9]
Hey @ssleptsov I just found out that adding keys dynamically to ninja keys make the keyboard navigation navigate randomly inside ninja keys. 

Is there a way to force render the list again, I believe this is specifically happening because we are adding the hot keys dynamically when the route changes like below.

```
hotKeys() {
      return [...this.conversationHotKeys, ...this.goToCommandHotKeys];
    },
```

The conversationHotkeys array gets added only if we're on a specific page.

Here's how it behaves.

https://user-images.githubusercontent.com/15716057/142809728-a2977ddc-f480-4c28-b8c5-e19d8d5c5b01.mp4

If there's an event to re initiate the hot keys, I think this will definitely resolve the issue.

**Comment by ssleptsov** [comment]
Hey @fayazara
It looks like a bug because it's already re-init hotkeys. 
I have pushed a quick fix, that I believe resolves the current issue. But I will take a closer look later.

Please try version `1.1.7` and let me know.
P.S I have also added "pass the action to handler" I saw it `chatwoot` fork, I think it can be useful, so included it too.

**Comment by fayazara** [comment]
@ssleptsov thank you for the fix and the update, unfortunately upgrading to this has made the command palette even more random and has some issues, for instance, some actions won't work unless we select three to four times. I will try to debug this and see what's causing it and also reproduce this and share a codesandbox with you, might help you fix it.

**Comment by fayazara** [comment]
@ssleptsov I tried using this update, unfortunately it has made the commands list unstable, I need to press enter 3 - 4 times to get some handlers working.

**Comment by ssleptsov** [comment]
> I will try to debug this and see what's causing it and also reproduce this and share a codesandbox with you, might help you fix it.

@fayazara do you have a codesandbox for it? That will help solve an issue.

**Comment by fayazara** [comment]
https://codesandbox.io/s/ninja-keys-demo-ryjw9?file=/src/App.vue

**Comment by ssleptsov** [comment]
@fayazara please update and try `1.1.9` version

**Comment by fayazara** [comment]
Seems to be working now, thank you.
